#!/usr/bin/python3
#
# Very simple jitsi top displaying some statistics from the jvb
#

import requests, time, datetime

resp = requests.get('http://127.0.0.1:8080/about/version')
version = resp.json()

while 1:
   print("\033[H\033[J%s %s on %s" % (version['name'], version['version'], version['os']))
   print()
   resp = requests.get('http://127.0.0.1:8080/colibri/stats')
   if resp.status_code != 200:
       # This means something went wrong.
       raise ApiError('GET /colibri/stats/ {}'.format(resp.status_code))
   data = resp.json()

   print("Current conference information")
   print("  Active          :% 3d" % data['conferences'])
   print("  Inactive        :% 3d" % data['inactive_conferences'])
   print("  Peer 2 peer     :% 3d" % data['p2p_conferences'])
   print("  Participants    :% 3d" % data['participants'])
   print("  Videostreams    :% 3d" % data['endpoints_sending_video'])
   print("  Audiostreams    :% 3d" % data['endpoints_sending_audio'])
   print("  Inactive clients:% 3d" % data['inactive_endpoints'])

   print("Network statistics")
   print("  Download: % 5d Kbps" % data['bit_rate_download'])
   print("  Upload  : % 5d Kbps" % data['bit_rate_upload'])
   print("  Avg RTT : % 5d ms" % data['rtt_aggregate'])

   print("ICE")
   print("  Succeed (relayed): % 3d (% 3d)" % (data['total_ice_succeeded'], data['total_ice_succeeded_relayed']))
   print("  Failed           : % 3d" % data['total_ice_failed'])

   print("Totals since server start")
   print("  Conferences       : % 3d" % data['total_conferences_created'])
   print("    Failed          : % 3d" % data['total_failed_conferences'])
   print("    Partially failed: % 3d" % data['total_partially_failed_conferences'])
   print("    Completed       : % 3d" % data['total_conferences_completed'])
   print("    Time            : %s" % datetime.timedelta(seconds=data['total_conference_seconds']))
   print("    Speaker changes : %s" % data['total_dominant_speaker_changes'])

   time.sleep(1)
